var searchData=
[
  ['implementing_20a_20solver_0',['implementing a solver',['../dc/d22/api_solvers.html#implementing-a-solver-1',1,'Implementing a Solver'],['../dc/df9/api_overview.html#implementing-a-solver',1,'Implementing a Solver']]],
  ['import_20errors_1',['Plot scripts fail with Python import errors',['../d7/d83/tools.html#plot-scripts-fail-with-python-import-errors',1,'']]],
  ['in_20directory_20mode_2',['Conversion script processes no files in directory mode',['../d7/d83/tools.html#conversion-script-processes-no-files-in-directory-mode',1,'']]],
  ['in_20solver_5fdir_20tt_3',['&lt;tt&gt;No executable solvers found in &lt;solver_dir&gt;&lt;/tt&gt;',['../d7/d83/tools.html#no-executable-solvers-found-in-solver_dir',1,'']]],
  ['in_20tt_20ggg_3a_3asolutions_3a_3adetail_20tt_20and_20expect_20callers_20to_20provide_4',['* These utilities live in &lt;tt&gt;ggg::solutions::detail&lt;/tt&gt; and expect callers to provide',['../d7/d06/namespaceggg.html#autotoc_md-these-utilities-live-in-gggsolutionsdetail-and-expect-callers-to-provide',1,'']]],
  ['in_20validators_5',['Using Built-in Validators',['../dc/df9/api_overview.html#using-built-in-validators',1,'']]],
  ['in_20your_20code_6',['Using the API in Your Code',['../da/d0d/quick_start.html#using-the-api-in-your-code',1,'']]],
  ['in_20your_20project_7',['Using Game Graph Gym in Your Project',['../d9/d87/install.html#using-game-graph-gym-in-your-project',1,'']]],
  ['include_20non_20solver_20binaries_8',['Benchmarks unexpectedly include non-solver binaries',['../d7/d83/tools.html#benchmarks-unexpectedly-include-non-solver-binaries',1,'']]],
  ['included_20games_20and_20solvers_9',['Included Games and Solvers',['../d8/de9/md__2home_2runner_2work_2ggg_2ggg_2docs_2games.html',1,'']]],
  ['index_10',['1) Time by game index',['../d7/d83/tools.html#autotoc_md1-time-by-game-index',1,'']]],
  ['index_2emd_11',['index.md',['../df/dcf/index_8md.html',1,'']]],
  ['indices_12',['* appropriate value conversion callables. Keys are written as numeric indices',['../d7/d06/namespaceggg.html#autotoc_md-appropriate-value-conversion-callables-keys-are-written-as-numeric-indices',1,'']]],
  ['info_13',['INFO',['../dd/de8/namespaceggg_1_1utils.html#a39f8b709ba73ab516698bae2f3892d53a551b723eafd6a31d444fcb2f5920fbd3',1,'ggg::utils']]],
  ['input_20file_20formats_14',['Input File Formats',['../d7/d83/tools.html#input_formats',1,'']]],
  ['install_2emd_15',['install.md',['../de/da9/install_8md.html',1,'']]],
  ['installation_16',['Installation',['../d9/d87/install.html#installation',1,'']]],
  ['integration_17',['integration',['../d9/d87/install.html#cmake-integration',1,'CMake Integration'],['../d9/d87/install.html#manual-integration',1,'Manual Integration'],['../dc/df9/api_overview.html#validator-integration',1,'Validator Integration']]],
  ['internal_20for_20creating_20compact_20json_20like_20strings_20and_20streaming_20maps_18',['* Small helpers (internal) for creating compact JSON-like strings and streaming maps.',['../d7/d06/namespaceggg.html#autotoc_md-small-helpers-internal-for-creating-compact-json-like-strings-and-streaming-maps',1,'']]],
  ['is_20performed_20on_20produced_20fragments_19',['* via static_cast&lt;std::size_t&gt;. No escaping is performed on produced fragments.',['../d7/d06/namespaceggg.html#autotoc_md-via-static_caststdsize_t-no-escaping-is-performed-on-produced-fragments',1,'']]],
  ['is_5fwon_5fby_5fplayer0_20',['is_won_by_player0',['../da/d7c/classggg_1_1solutions_1_1RSolution.html#abf1ceef37b260697ae1cc924a31bfdbd',1,'ggg::solutions::RSolution']]],
  ['is_5fwon_5fby_5fplayer1_21',['is_won_by_player1',['../da/d7c/classggg_1_1solutions_1_1RSolution.html#a2df4afb6ea94fa5711d4947c476b9f53',1,'ggg::solutions::RSolution']]],
  ['isolution_22',['isolution',['../d9/d72/classggg_1_1solutions_1_1ISolution.html#a1b0590c276c082831034052d0b8073a7',1,'ggg::solutions::ISolution::ISolution()'],['../d9/d72/classggg_1_1solutions_1_1ISolution.html',1,'ggg::solutions::ISolution']]],
  ['isolution_20graphtype_23',['isolution graphtype',['../dc/d22/api_solvers.html#isolutiongraphtype-1',1,'ISolution&lt;GraphType&gt;'],['../dc/df9/api_overview.html#isolutiongraphtype',1,'ISolution&lt;GraphType&gt;']]],
  ['isolution_2ehpp_24',['isolution.hpp',['../df/d5c/isolution_8hpp.html',1,'']]],
  ['issues_25',['Common Issues',['../d9/d87/install.html#common-issues',1,'']]]
];
