var searchData=
[
  ['back_0',['back',['../d5/d5a/classUintqueue.html#ae7886f7d6b050382db416a98e1e6d082',1,'Uintqueue']]],
  ['back2_1',['back2',['../d5/d5a/classUintqueue.html#a3b586ab49ad39aac424724416f82e40b',1,'Uintqueue']]],
  ['basic_20build_2',['Basic Build',['../d9/d87/install.html#basic-build',1,'']]],
  ['bc_3a_20command_20not_20found_20tt_3',['&lt;tt&gt;benchmark.sh&lt;/tt&gt; fails with &lt;tt&gt;bc: command not found&lt;/tt&gt;',['../d7/d83/tools.html#benchmarksh-fails-with-bc-command-not-found',1,'']]],
  ['benchmark_20existing_20test_20suite_20corpus_4',['Working example 2: benchmark existing test-suite corpus',['../d7/d83/tools.html#working-example-2-benchmark-existing-test-suite-corpus',1,'']]],
  ['benchmark_20generated_20parity_20games_5',['Working example 1: benchmark generated parity games',['../d7/d83/tools.html#working-example-1-benchmark-generated-parity-games',1,'']]],
  ['benchmark_20output_6',['Plotting benchmark output',['../d7/d83/tools.html#plotting-benchmark-output',1,'']]],
  ['benchmark_20runner_3a_20tt_20benchmark_20sh_20tt_7',['Benchmark runner: &lt;tt&gt;benchmark.sh&lt;/tt&gt;',['../d7/d83/tools.html#benchmark-runner-benchmarksh',1,'']]],
  ['benchmark_20sh_20tt_8',['Benchmark runner: &lt;tt&gt;benchmark.sh&lt;/tt&gt;',['../d7/d83/tools.html#benchmark-runner-benchmarksh',1,'']]],
  ['benchmark_20sh_20tt_20fails_20with_20tt_20bc_3a_20command_20not_20found_20tt_9',['&lt;tt&gt;benchmark.sh&lt;/tt&gt; fails with &lt;tt&gt;bc: command not found&lt;/tt&gt;',['../d7/d83/tools.html#benchmarksh-fails-with-bc-command-not-found',1,'']]],
  ['benchmark_20sh_20tt_20fails_20with_20tt_20timeout_3a_20command_20not_20found_20tt_10',['&lt;tt&gt;benchmark.sh&lt;/tt&gt; fails with &lt;tt&gt;timeout: command not found&lt;/tt&gt;',['../d7/d83/tools.html#benchmarksh-fails-with-timeout-command-not-found',1,'']]],
  ['benchmarking_20scripts_11',['Benchmarking Scripts',['../d7/d83/tools.html#benchmarking-scripts',1,'']]],
  ['benchmarks_20unexpectedly_20include_20non_20solver_20binaries_12',['Benchmarks unexpectedly include non-solver binaries',['../d7/d83/tools.html#benchmarks-unexpectedly-include-non-solver-binaries',1,'']]],
  ['bibliography_13',['Bibliography',['../d0/de3/citelist.html',1,'']]],
  ['binaries_14',['Benchmarks unexpectedly include non-solver binaries',['../d7/d83/tools.html#benchmarks-unexpectedly-include-non-solver-binaries',1,'']]],
  ['boost_20graph_20library_20features_20where_20possible_15',['Use Boost Graph Library features where possible',['../d0/d3f/developing.html#use-boost-graph-library-features-where-possible',1,'']]],
  ['buechigraphvalidator_16',['BuechiGraphValidator',['../dd/db6/tools_2buchi_2solvers_2attractor_8cpp.html#a509e5c0771fdbf0d7f1f316da88c4289',1,'attractor.cpp']]],
  ['build_17',['build',['../d9/d87/install.html#basic-build',1,'Basic Build'],['../d9/d87/install.html#complete-build',1,'Complete Build']]],
  ['build_20options_18',['Build Options',['../d9/d87/install.html#build-options',1,'']]],
  ['building_20game_20graph_20gym_19',['Building Game Graph Gym',['../d9/d87/install.html',1,'']]],
  ['building_20ggg_20',['Building GGG',['../d9/d87/install.html#building-ggg',1,'']]],
  ['building_20tools_20and_20solvers_21',['Building Tools and Solvers',['../da/d0d/quick_start.html#building-tools-and-solvers',1,'']]],
  ['builds_22',['builds',['../d9/d87/install.html#debug-builds',1,'Debug Builds'],['../d9/d87/install.html#performance-builds',1,'Performance Builds']]],
  ['built_20in_20validators_23',['Using Built-in Validators',['../dc/df9/api_overview.html#using-built-in-validators',1,'']]],
  ['but_20no_20curves_20appear_24',['Plot scripts run, but no curves appear',['../d7/d83/tools.html#plot-scripts-run-but-no-curves-appear',1,'']]],
  ['by_20game_20index_25',['1) Time by game index',['../d7/d83/tools.html#autotoc_md1-time-by-game-index',1,'']]],
  ['by_20game_20type_26',['3) Performance by game type',['../d7/d83/tools.html#autotoc_md3-performance-by-game-type',1,'']]],
  ['by_20vertex_20count_20scalability_27',['2) Mean time by vertex count (scalability)',['../d7/d83/tools.html#autotoc_md2-mean-time-by-vertex-count-scalability',1,'']]]
];
