var searchData=
[
  ['test_20coverage_0',['Test Coverage',['../d0/d3f/developing.html#test-coverage',1,'']]],
  ['test_20suite_20corpus_1',['Working example 2: benchmark existing test-suite corpus',['../d7/d83/tools.html#working-example-2-benchmark-existing-test-suite-corpus',1,'']]],
  ['testing_2',['Testing',['../d0/d3f/developing.html#testing',1,'']]],
  ['tests_3',['tests',['../d0/d3f/developing.html#running-tests',1,'Running Tests'],['../d0/d3f/developing.html#writing-tests',1,'Writing Tests']]],
  ['the_20api_20in_20your_20code_4',['Using the API in Your Code',['../da/d0d/quick_start.html#using-the-api-in-your-code',1,'']]],
  ['these_20utilities_20live_20in_20tt_20ggg_3a_3asolutions_3a_3adetail_20tt_20and_20expect_20callers_20to_20provide_5',['* These utilities live in &lt;tt&gt;ggg::solutions::detail&lt;/tt&gt; and expect callers to provide',['../d7/d06/namespaceggg.html#autotoc_md-these-utilities-live-in-gggsolutionsdetail-and-expect-callers-to-provide',1,'']]],
  ['time_20by_20game_20index_6',['1) Time by game index',['../d7/d83/tools.html#autotoc_md1-time-by-game-index',1,'']]],
  ['time_20by_20vertex_20count_20scalability_7',['2) Mean time by vertex count (scalability)',['../d7/d83/tools.html#autotoc_md2-mean-time-by-vertex-count-scalability',1,'']]],
  ['timeout_3a_20command_20not_20found_20tt_8',['&lt;tt&gt;benchmark.sh&lt;/tt&gt; fails with &lt;tt&gt;timeout: command not found&lt;/tt&gt;',['../d7/d83/tools.html#benchmarksh-fails-with-timeout-command-not-found',1,'']]],
  ['to_20end_20cli_20workflow_20example_9',['End-to-end CLI workflow example',['../d7/d83/tools.html#end-to-end-cli-workflow-example',1,'']]],
  ['to_20end_20workflow_10',['Typical end-to-end workflow',['../d7/d83/tools.html#typical-end-to-end-workflow',1,'']]],
  ['to_20produce_20no_20output_20file_11',['&lt;tt&gt;ggg_to_dot.py&lt;/tt&gt; appears to produce no output file',['../d7/d83/tools.html#ggg_to_dotpy-appears-to-produce-no-output-file',1,'']]],
  ['to_20provide_12',['* These utilities live in &lt;tt&gt;ggg::solutions::detail&lt;/tt&gt; and expect callers to provide',['../d7/d06/namespaceggg.html#autotoc_md-these-utilities-live-in-gggsolutionsdetail-and-expect-callers-to-provide',1,'']]],
  ['to_5fjson_13',['to_json',['../da/da0/classggg_1_1solutions_1_1SSolution.html#a6e5006b33bf13348df5b7b71977c2452',1,'ggg::solutions::SSolution::to_json()'],['../d9/db5/namespaceggg_1_1strategy.html#a7fb5eca0a25ce1dc614cd245ab0b12d8',1,'ggg::strategy::to_json(const MixingStrategy&lt; GraphType &gt; &amp;m)'],['../d9/db5/namespaceggg_1_1strategy.html#aafd6f82ff8857254561c61378ae9f317',1,'ggg::strategy::to_json(const FiniteMemoryStrategy&lt; GraphType &gt; &amp;fm)'],['../d9/db5/namespaceggg_1_1strategy.html#acf25fd0deb92662090492b79271302bf',1,'ggg::strategy::to_json(const DeterministicStrategy&lt; GraphType &gt; &amp;s)'],['../dd/d77/classggg_1_1solutions_1_1RSSolution.html#aa63318adec5f7202a0fe4172297afe01',1,'ggg::solutions::RSSolution::to_json()'],['../d3/da4/classggg_1_1solutions_1_1RSQSolution.html#a1d880da7ffbba54f842466d4de511077',1,'ggg::solutions::RSQSolution::to_json()'],['../da/d7c/classggg_1_1solutions_1_1RSolution.html#ab03ad7493fc3d42ac0cbb436c4f6e6a5',1,'ggg::solutions::RSolution::to_json()'],['../dd/d5b/classggg_1_1solutions_1_1QSolution.html#a5e3a0ebfac82892ee35c1bddfca9789d',1,'ggg::solutions::QSolution::to_json()'],['../d9/d72/classggg_1_1solutions_1_1ISolution.html#aac9d15138b97504a0db3c2bacabc27c6',1,'ggg::solutions::ISolution::to_json()']]],
  ['to_5fstream_14',['to_stream',['../d9/db5/namespaceggg_1_1strategy.html#ac52ed794c5ce70725acabd6eb7d3a916',1,'ggg::strategy::to_stream(std::ostream &amp;os, const DeterministicStrategy&lt; GraphType &gt; &amp;s)'],['../d9/db5/namespaceggg_1_1strategy.html#a462dc8d797736f9fab5d5821abcbe41f',1,'ggg::strategy::to_stream(std::ostream &amp;os, const FiniteMemoryStrategy&lt; GraphType &gt; &amp;fm)'],['../d9/db5/namespaceggg_1_1strategy.html#aa5919882eccf7066cbdc1b0329ebeec2',1,'ggg::strategy::to_stream(std::ostream &amp;os, const MixingStrategy&lt; GraphType &gt; &amp;m)']]],
  ['tools_15',['Command-line tools',['../d7/d83/tools.html',1,'']]],
  ['tools_20and_20solvers_16',['Building Tools and Solvers',['../da/d0d/quick_start.html#building-tools-and-solvers',1,'']]],
  ['tools_2emd_17',['tools.md',['../d1/d29/tools_8md.html',1,'']]],
  ['tools_2fbuchi_2fsolvers_2fattractor_2ecpp_18',['attractor.cpp',['../dd/db6/tools_2buchi_2solvers_2attractor_8cpp.html',1,'']]],
  ['tools_2fmean_5fpayoff_2fsolvers_2fmsca_2ecpp_19',['msca.cpp',['../d7/df8/tools_2mean__payoff_2solvers_2msca_8cpp.html',1,'']]],
  ['tools_2fmean_5fpayoff_2fsolvers_2fmse_2ecpp_20',['mse.cpp',['../de/dec/tools_2mean__payoff_2solvers_2mse_8cpp.html',1,'']]],
  ['tools_2fparity_2fsolvers_2fpriority_5fpromotion_2ecpp_21',['priority_promotion.cpp',['../dd/de0/tools_2parity_2solvers_2priority__promotion_8cpp.html',1,'']]],
  ['tools_2fparity_2fsolvers_2fprogressive_5fsmall_5fprogress_5fmeasures_2ecpp_22',['progressive_small_progress_measures.cpp',['../d6/d77/tools_2parity_2solvers_2progressive__small__progress__measures_8cpp.html',1,'']]],
  ['tools_2fparity_2fsolvers_2frecursive_2ecpp_23',['recursive.cpp',['../dc/d88/tools_2parity_2solvers_2recursive_8cpp.html',1,'']]],
  ['tools_2fstochastic_5fdiscounted_2fsolvers_2fobjective_2ecpp_24',['objective.cpp',['../d8/dd7/tools_2stochastic__discounted_2solvers_2objective_8cpp.html',1,'']]],
  ['tools_2fstochastic_5fdiscounted_2fsolvers_2fstrategy_2ecpp_25',['strategy.cpp',['../d7/d93/tools_2stochastic__discounted_2solvers_2strategy_8cpp.html',1,'']]],
  ['tools_2fstochastic_5fdiscounted_2fsolvers_2fvalue_2ecpp_26',['value.cpp',['../d2/dd1/tools_2stochastic__discounted_2solvers_2value_8cpp.html',1,'']]],
  ['trace_27',['TRACE',['../dd/de8/namespaceggg_1_1utils.html#a39f8b709ba73ab516698bae2f3892d53a2d3e4144aa384b18849ab9a8abad74d6',1,'ggg::utils']]],
  ['troubleshooting_28',['troubleshooting',['../d7/d83/tools.html#troubleshooting-1',1,'Troubleshooting'],['../d9/d87/install.html#troubleshooting',1,'Troubleshooting']]],
  ['tt_20benchmark_20sh_20tt_29',['Benchmark runner: &lt;tt&gt;benchmark.sh&lt;/tt&gt;',['../d7/d83/tools.html#benchmark-runner-benchmarksh',1,'']]],
  ['tt_20benchmark_20sh_20tt_20fails_20with_20tt_20bc_3a_20command_20not_20found_20tt_30',['&lt;tt&gt;benchmark.sh&lt;/tt&gt; fails with &lt;tt&gt;bc: command not found&lt;/tt&gt;',['../d7/d83/tools.html#benchmarksh-fails-with-bc-command-not-found',1,'']]],
  ['tt_20benchmark_20sh_20tt_20fails_20with_20tt_20timeout_3a_20command_20not_20found_20tt_31',['&lt;tt&gt;benchmark.sh&lt;/tt&gt; fails with &lt;tt&gt;timeout: command not found&lt;/tt&gt;',['../d7/d83/tools.html#benchmarksh-fails-with-timeout-command-not-found',1,'']]],
  ['tt_20ggg_3a_3asolutions_3a_3adetail_20tt_20and_20expect_20callers_20to_20provide_32',['* These utilities live in &lt;tt&gt;ggg::solutions::detail&lt;/tt&gt; and expect callers to provide',['../d7/d06/namespaceggg.html#autotoc_md-these-utilities-live-in-gggsolutionsdetail-and-expect-callers-to-provide',1,'']]],
  ['tt_20ggg_5fmean_5fpayoff_5fgenerate_20tt_33',['Mean-payoff generator (&lt;tt&gt;ggg_mean_payoff_generate&lt;/tt&gt;)',['../d7/d83/tools.html#mean-payoff-generator-ggg_mean_payoff_generate',1,'']]],
  ['tt_20ggg_5fparity_5fgenerate_20tt_34',['Parity generator (&lt;tt&gt;ggg_parity_generate&lt;/tt&gt;)',['../d7/d83/tools.html#parity-generator-ggg_parity_generate',1,'']]],
  ['tt_20ggg_5fstochastic_5fdiscounted_5fgenerate_20tt_35',['Stochastic discounted generator (&lt;tt&gt;ggg_stochastic_discounted_generate&lt;/tt&gt;)',['../d7/d83/tools.html#stochastic-discounted-generator-ggg_stochastic_discounted_generate',1,'']]],
  ['tt_20ggg_5fto_5fdot_20py_20tt_36',['3) &lt;tt&gt;ggg_to_dot.py&lt;/tt&gt;',['../d7/d83/tools.html#autotoc_md3-ggg_to_dotpy',1,'']]],
  ['tt_20ggg_5fto_5fdot_20py_20tt_20appears_20to_20produce_20no_20output_20file_37',['&lt;tt&gt;ggg_to_dot.py&lt;/tt&gt; appears to produce no output file',['../d7/d83/tools.html#ggg_to_dotpy-appears-to-produce-no-output-file',1,'']]],
  ['tt_20hoa_5fto_5fdot_20py_20tt_38',['2) &lt;tt&gt;hoa_to_dot.py&lt;/tt&gt;',['../d7/d83/tools.html#autotoc_md2-hoa_to_dotpy',1,'']]],
  ['tt_20no_20dot_20files_20tt_20empty_20result_20set_39',['&lt;tt&gt;No .dot files&lt;/tt&gt; / empty result set',['../d7/d83/tools.html#no-dot-files--empty-result-set',1,'']]],
  ['tt_20no_20executable_20solvers_20found_20in_20solver_5fdir_20tt_40',['&lt;tt&gt;No executable solvers found in &lt;solver_dir&gt;&lt;/tt&gt;',['../d7/d83/tools.html#no-executable-solvers-found-in-solver_dir',1,'']]],
  ['tt_20pgsolver_5fto_5fggg_20py_20tt_41',['1) &lt;tt&gt;pgsolver_to_ggg.py&lt;/tt&gt;',['../d7/d83/tools.html#autotoc_md1-pgsolver_to_gggpy',1,'']]],
  ['type_42',['3) Performance by game type',['../d7/d83/tools.html#autotoc_md3-performance-by-game-type',1,'']]],
  ['types_43',['types',['../d0/ddd/api_graphs.html#adding-new-game-types',1,'Adding New Game Types'],['../dc/df9/api_overview.html#adding-new-game-types-1',1,'Adding New Game Types'],['../dc/d22/api_solvers.html#combined-solution-types-1',1,'Combined Solution Types'],['../dc/df9/api_overview.html#combined-solution-types',1,'Combined Solution Types'],['../dc/df9/api_overview.html#solution-types',1,'Solution Types'],['../dc/d22/api_solvers.html#solution-types-1',1,'Solution Types']]],
  ['typical_20end_20to_20end_20workflow_44',['Typical end-to-end workflow',['../d7/d83/tools.html#typical-end-to-end-workflow',1,'']]]
];
